[package]
name = "variable-len-reader"
version = "0.3.0"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "A library for reading variable length data."
readme = "README.md"
license = "MIT"
repository = "https://github.com/xuxiaocheng0201/variable-len-reader/"
keywords = ["varint", "io"]

[dependencies]
varint-rs = { version = "^2.2", default-features = false, features = ["std"] }

[features]
default = ["string"]

signed = ["varint-rs/signed"]
vec_u8 = []
string = ["vec_u8"]
