[package]
name = "variable-len-reader"
version = "0.3.2"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "A library for reading/writing variable length data."
readme = "README.md"
license = "MIT"
repository = "https://github.com/xuxiaocheng0201/variable-len-reader/"
keywords = ["varint", "io"]

[features]
default = ["raw", "signed", "string"]

raw = []
signed = []
vec_u8 = []
string = ["vec_u8"]
async = []

[badges]
maintenance = { status = "actively-developed" }
