[package]
name = "variable-len-reader"
version = "0.5.0"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "A library for reading/writing variable length data."
readme = "README.md"
license = "MIT"
repository = "https://github.com/xuxiaocheng0201/variable-len-reader/"
categories = ["encoding", "parser-implementations"]
keywords = ["varint", "zigzag", "io", "async"]

[dependencies]
async-trait = { version = "0", optional = true, default-features = false }
tokio = { version = "1", optional = true, default-features = false }

[features]
default = ["raw", "signed", "string"]

raw = []
signed = []
vec_u8 = []
string = ["vec_u8"]

async = ["async-trait", "tokio/io-util"]
async_default = ["async_raw", "async_signed", "async_string"]
async_raw = ["async"]
async_signed = ["async"]
async_vec_u8 = ["async"]
async_string = ["async_vec_u8"]

[badges]
maintenance = { status = "actively-developed" }
