[package]
name = "variable-len-reader"
version = "1.0.0"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "A library for reading/writing variable length data. Support AsyncReadExt/AsyncWriteExt in tokio."
readme = "README.md"
license = "MIT"
repository = "https://github.com/xuxiaocheng0201/variable-len-reader/"
documentation = "https://docs.rs/variable-len-reader/"
categories = ["encoding", "parser-implementations"]
keywords = ["varint", "zigzag", "io", "async"]
exclude = ["test-builds.bat"]

[dependencies]
#serde = { version = "^1", optional = true }
pin-project-lite = { version = "~0.2", optional = true }
tokio = { version = "^1", optional = true, default-features = false }
bytes = { version = "^1", optional = true } # Support crate::bufs::*

[dev-dependencies]
anyhow = "^1.0"
tokio = { version = "^1", features = ["macros", "rt-multi-thread", "net", "time", "io-util", "sync"] }

[features]
default = ["raw", "varint", "signed", "vec_u8", "string", "async_default", "bools"]

raw = []
bools = []
varint = ["raw"]
long_varint = ["varint"]
signed = ["varint"]
long_signed = ["signed", "long_varint"]
vec_u8 = ["varint"]
string = ["vec_u8"]
#serde = ["dep:serde"]

async = ["dep:pin-project-lite", "dep:tokio"]
async_default = ["async_raw", "async_varint", "async_signed", "async_vec_u8", "async_string"]
async_raw = ["async"]
async_bools = ["async"]
async_varint = ["async_raw"]
async_long_varint = ["async_varint"]
async_signed = ["async_varint"]
async_long_signed = ["async_signed", "async_long_varint"]
async_vec_u8 = ["async_varint"]
async_string = ["async_vec_u8"]
#async_serde = ["async", "dep:serde"]

[build-dependencies]
reportme = "~0.2"

[badges]
maintenance = { status = "actively-developed" }
