[package]
name = "variable-len-reader"
version = "0.2.1"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "A library for reading variable length data."
readme = "README.md"
license = "MIT"
repository = "https://github.com/xuxiaocheng0201/variable-len-reader/"
keywords = ["varint"]

[dependencies]

[features]
default = ["str"]

primitive = []
variable-len = ["primitive"]
str = ["variable-len"]
