cargo build --no-default-features --features "sync"
cargo build --no-default-features --features "sync_raw"
cargo build --no-default-features --features "sync_raw_size"
cargo build --no-default-features --features "sync_bools"
cargo build --no-default-features --features "sync_varint"
cargo build --no-default-features --features "sync_varint_size"
cargo build --no-default-features --features "sync_varint_long"
cargo build --no-default-features --features "sync_varint_long_size"
cargo build --no-default-features --features "sync_signed_varint"
cargo build --no-default-features --features "sync_signed_varint_size"
cargo build --no-default-features --features "sync_signed_varint_long"
cargo build --no-default-features --features "sync_signed_varint_long_size"
cargo build --no-default-features --features "sync_float_varint"
cargo build --no-default-features --features "sync_float_varint_long"
cargo build --no-default-features --features "sync_vec_u8"
cargo build --no-default-features --features "sync_string"
cargo build --no-default-features --features "sync_default"
cargo build --no-default-features --features "sync_full"
cargo build --no-default-features --features "std,sync_full"
cargo build --no-default-features --features "sync_full,bytes"

cargo build --no-default-features --features "async"
cargo build --no-default-features --features "async_raw"
cargo build --no-default-features --features "async_raw_size"
cargo build --no-default-features --features "async_bools"
cargo build --no-default-features --features "async_varint"
cargo build --no-default-features --features "async_varint_size"
cargo build --no-default-features --features "async_long_varint"
cargo build --no-default-features --features "async_varint_size,async_long_varint"
cargo build --no-default-features --features "async_signed"
cargo build --no-default-features --features "async_long_signed"
cargo build --no-default-features --features "async_float"
cargo build --no-default-features --features "async_long_float"
cargo build --no-default-features --features "async_vec_u8"
cargo build --no-default-features --features "async_string"
cargo build --no-default-features --features "async_default"
cargo build --no-default-features --features "async_full"

cargo build --no-default-features --features "default"
cargo build --no-default-features --features "full"

cargo test --no-default-features --features "full,bytes" --lib
cargo test --features "async_default" --doc
